version: 2
updates:
  - package-ecosystem: 'pip'
    directories:
      - '**/*'
    schedule:
      interval: 'daily'
    groups:
      production-dependencies:
        dependency-type: 'production'
      development-dependencies:
        dependency-type: 'development'