// This file transforms interfaces into JSON objects to be used by swagger

const path = require("path");
const tjs = require("typescript-json-schema");
const fs = require("fs");

const settings = {
  required: true,
  ref: false,
};
const compilerOptions = {
  strictNullChecks: true,
};

const schemas_path = "src/types/schemas.ts"
const program = tjs.getProgramFromFiles([path.resolve(schemas_path)], compilerOptions, "./");

const schema = tjs.generateSchema(program, "*", settings);
fs.writeFileSync(
  "build/_schema.ts",
  "// THIS FILE IS AUTO-GENERATED BY SCHEMAGENERATOR.JS\n" +
  "export const _schema = " + JSON.stringify(schema, null, 4) + ";"
);
